### ISSUE TITLE
Uso de docker y AWS

### ISSUE THREAD

**Issue by caroacostatovany** [lecepe00/PageRank-eigenvectores-eigenvalores#13]
@cecyar y @lecepe00 , aquí pueden poner más evidencia que utilizamos docker y AWS

**Comment by caroacostatovany** [comment]
Esta es la prueba de poder levantar una instancia en AWS, levantándo jupyter notebook con docker

![image](https://user-images.githubusercontent.com/8687470/101647436-5aa26280-39fe-11eb-9e81-b0d735b7b187.png)

**Comment by caroacostatovany** [comment]
Clonar el repo dentro de la instancia y del jupyter: 
![image](https://user-images.githubusercontent.com/8687470/101649077-1adc7a80-3a00-11eb-9d4e-048688c56b3d.png)

**Comment by caroacostatovany** [comment]
Commit desde jupyter : 

![image](https://user-images.githubusercontent.com/8687470/101651422-ab1bbf00-3a02-11eb-8f01-d36185e110bd.png)

**Comment by lecepe00** [comment]
Agregando commit desde la instancia:

![image](https://user-images.githubusercontent.com/66655656/101669639-d2c95200-3a17-11eb-9991-16b69d05ec44.png)

**Comment by cecyar** [comment]
Adjunto evidencia de mis actualizaciones y commit desde la instancia:
![image](https://user-images.githubusercontent.com/66655647/101696021-108ba200-3a3b-11eb-8daf-d271741bd693.png)

**Comment by lecepe00** [comment]
Se cierra issue con evidencia de los 3 integrantes del equipo realizando commits desde la instancia de AWS.
