### ISSUE TITLE
Resultados de la implementación

### ISSUE THREAD

**Issue by lecepe00** [lecepe00/PageRank-eigenvectores-eigenvalores#9]
Reporte de resultados de la implementación en el trabajo escrito.

**Comment by caroacostatovany** [comment]
De igual forma ya agregué un ejemplo en el trabajo escrito en: https://github.com/lecepe00/PageRank-eigenvectores-eigenvalores/tree/main/Trabajo_Escrito

**Comment by lecepe00** [comment]
Se cierra issue con sección finalizada en el reporte escrito.
